// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSQ26nZhuzsetPzYO6M8HawRBMBuw5cF0',
    appId: '1:815785620616:web:21ca5a6a9715a27c4f1b3d',
    messagingSenderId: '815785620616',
    projectId: 'smartai-5077f',
    authDomain: 'smartai-5077f.firebaseapp.com',
    storageBucket: 'smartai-5077f.firebasestorage.app',
    measurementId: 'G-6GSY0K9VK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0g3h8dLXNnrqDEhHlwmpuhsHTbWIc4PA',
    appId: '1:815785620616:android:10cb9e66f4fa75274f1b3d',
    messagingSenderId: '815785620616',
    projectId: 'smartai-5077f',
    storageBucket: 'smartai-5077f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVfxc_EQkBgfT4MnVs10f5rsgPx13p4xo',
    appId: '1:815785620616:ios:cd38f2f103472baf4f1b3d',
    messagingSenderId: '815785620616',
    projectId: 'smartai-5077f',
    storageBucket: 'smartai-5077f.firebasestorage.app',
    iosBundleId: 'com.example.smartAiAssistant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVfxc_EQkBgfT4MnVs10f5rsgPx13p4xo',
    appId: '1:815785620616:ios:cd38f2f103472baf4f1b3d',
    messagingSenderId: '815785620616',
    projectId: 'smartai-5077f',
    storageBucket: 'smartai-5077f.firebasestorage.app',
    iosBundleId: 'com.example.smartAiAssistant',
  );
}
